version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step2/myappF
    overwrite: yes

permissions:
#  - object: /
  - object: /home/ec2-user/app/step2/myappF
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: beforeInstall.bash
  AfterInstall:
    - location: deploy.sh