version: 0.0
os: linux
files:
  - source: /
    destination: /usr/local/myappF
    overwrite: yes

permissions:
  - object: /usr/local/myappf
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user