name: FRONTEND-Release-Deploy # Workflow 이름
on: # Event 감지
  push:
    branches:
      - release/1.0 # 마스터 브랜치의 푸쉬가 일어날 때 CI/CD를 진행하겠다는 뜻

jobs: # Job 설정
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./fronted

    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v2
      - name: Check Node v # Node v 확인
        run: node -v
        working-directory: ${{ env.working-directory }}
      - name: Install Dependencies # 의존 파일 설치
        run: yarn install --frozen-lockfile
        working-directory: ${{ env.working-directory }}

      - name: Build # React Build
        run: yarn build
        working-directory: ${{ env.working-directory }}

      - name: zip create
        run:  zip -qq -r ./hellomyteam-front-release.zip .
        working-directory: ${{ env.working-directory }}
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3 # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp —region ap-northeast-2 ./hellomyteam-front-release.zip s3://hellomyteam-github-action-s3-bucket/hellomyteam-front-release/hellomyteam-front-release.zip
        working-directory: ${{ env.working-directory }}
      - name: Deploy # Deploy to EC2
        run: aws deploy create-deployment
          —application-name hellomyteam-webservice
          —deployment-config-name CodeDeployDefault.AllAtOnce
          —deployment-group-name hellomyteam-webservice-group
          —s3-location bucket=hellomyteam-github-action-s3-bucket,key=hellomyteam-front-release/hellomyteam-front-release.zip,bundleType=zip
        working-directory: ${{ env.working-directory }}