name: FRONTEND-Release-Deploy # Workflow 이름
on:
  release:
    types: [push] # (1) push시 자동으로 실행됩니다.
  push:
    branches: [release] # (2) release 브랜치에서 동작합니다!
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # (4) 해당 스크립트를 작동할 OS 입니다.

    steps:
      - name: Checkout source code. # Repo checkout
        uses: actions/checkout@v2

      - name: Check Node v # Node v 확인
        run: node -v

      - name: Install Dependencies # 의존 파일 설치
        run: npm install --frozen-lockfile

      - name: Build # React Build
        run: npm build

      - name: zip create
        run: zip -qq -r ./hellomyteam-front-release.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload to S3 # Upload build file to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --region ap-northeast-2 ./hellomyteam-front-release.zip s3://hellomyteam-github-action-s3-bucket/hellomyteam-front-release/hellomyteam-front-release.zip

      - name: Deploy # Deploy to EC2
        run: aws deploy create-deployment
          --application-name hellomyteam-webservice
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name hellomyteam-webservice-group
          --s3-location bucket=hellomyteam-github-action-s3-bucket,key=hellomyteam-front-release/hellomyteam-front-release.zip,bundleType=zip











